# Generated by Django 3.2 on 2021-05-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('doc_date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[(1, 'prescription'), (2, 'bill')], max_length=50)),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
