# Generated by Django 3.2.2 on 2021-06-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_cons_type'),
        ('patients', '0005_doctor_secretary'),
        ('bills', '0004_auto_20210605_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultation'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
    ]
