# Generated by Django 3.2.2 on 2021-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20210605_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='doc_type',
            field=models.CharField(choices=[(1, 'prescription'), (2, 'bill')], max_length=50, null=True),
        ),
    ]
