# Generated by Django 3.2.2 on 2021-06-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_cons_type'),
        ('patients', '0005_doctor_secretary'),
        ('bills', '0006_alter_bill_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultation'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doc_type',
            field=models.CharField(blank=True, choices=[(1, 'prescription'), (2, 'bill')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
    ]
