# Generated by Django 3.2.2 on 2021-06-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20210605_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='consultation',
        ),
    ]
