# Generated by Django 3.2.2 on 2021-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_bill_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
