# Generated by Django 3.2.2 on 2021-06-12 13:32

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_bill_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='services',
            field=models.JSONField(default=bills.models.Bill.service_default),
        ),
    ]
