# Generated by Django 3.2.2 on 2021-06-06 09:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import prescriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0003_alter_consultation_cons_type'),
        ('patients', '0005_doctor_secretary'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('doc_date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(blank=True, choices=[(1, 'prescription'), (2, 'bill')], max_length=50, null=True)),
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_data', models.JSONField(default=prescriptions.models.prescription.drugs_default)),
                ('drugs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), null=True, size=3), blank=True, null=True, size=3)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
