# Generated by Django 3.2.2 on 2021-06-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='drugs',
        ),
    ]
