# Generated by Django 3.2.2 on 2021-06-06 10:06

from django.db import migrations, models
import prescriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescription_drug_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='drug_data',
            field=models.JSONField(default=prescriptions.models.prescription.drugs_default),
        ),
    ]
