# Generated by Django 3.2.2 on 2021-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_prescription_drug_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
