# Generated by Django 3.2 on 2021-05-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
