# Generated by Django 3.2 on 2021-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.CharField(choices=[(1, 'Lequid'), (2, 'Pill'), (3, 'Vaccine')], max_length=50, null=True),
        ),
    ]
