# Generated by Django 3.2.2 on 2021-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
