# Generated by Django 3.2 on 2021-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210505_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
