# Generated by Django 3.2.2 on 2021-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210613_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10, null=True),
        ),
    ]
