# Generated by Django 3.2 on 2021-05-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_doctor_secretary'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('cons_type', models.CharField(max_length=50)),
                ('examine', models.CharField(max_length=50)),
                ('conclusion', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
