# Generated by Django 3.2.2 on 2021-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_cons_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='cons_type',
            field=models.CharField(choices=[(1, 'urgent'), (2, 'normal')], max_length=50),
        ),
    ]
